language: generic 
sudo: required
services:
  - docker 

before_install:
  - docker build -t nnethercott/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nnethercott/react-test npm test

after_success:
  - docker build -t nnethercott/multi-client ./client 
  - docker build -t nnethercott/multi-nginx ./nginx 
  - docker build -t nnethercott/multi-server ./server 
  - docker build -t nnethercott/multi-worker ./worker 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nnethercott/multi-client
  - docker push nnethercott/multi-nginx 
  - docker push nnethercott/multi-server 
  - docker push nnethercott/multi-worker
