language: generic 
sudo: required
services:
  - docker 

before_install:
  - docker build -t nnethercott/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nnethercott/react-test npm test

after_success:
  - docker build -t nnethercott/multi-client ./client 
  - docker build -t nnethercott/multi-nginx ./nginx 
  - docker build -t nnethercott/multi-server ./server 
  - docker build -t nnethercott/multi-worker ./worker 